# Generated by Django 6.1.1 on 2026-09-20 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('sobrenome', models.CharField(blank=True, max_length=120)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('foto', models.ImageField(blank=True, upload_to='membros/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bio', models.TextField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['nome', 'sobrenome'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('categoria', models.CharField(max_length=100)),
                ('resumo', models.CharField(max_length=300)),
                ('descricao', models.TextField()),
                ('cliente', models.CharField(blank=True, max_length=160)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('imagem_capa', models.ImageField(blank=True, upload_to='projetos/capas/')),
                ('url_projeto', models.URLField(blank=True)),
                ('tecnologias', models.TextField(blank=True, help_text='Separe cada tecnologia por vírgula.')),
                ('publicado', models.BooleanField(default=False)),
                ('destaque', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-destaque', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImagemProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='projetos/galeria/')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='aplicacao_cerrado.projeto')),
            ],
            options={
                'verbose_name': 'Imagem do projeto',
                'verbose_name_plural': 'Imagens do projeto',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes', to='aplicacao_cerrado.membro')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='aplicacao_cerrado.projeto')),
            ],
            options={
                'verbose_name': 'Participação',
                'verbose_name_plural': 'Participações',
                'ordering': ['ordem', 'membro__nome'],
                'constraints': [models.UniqueConstraint(fields=('projeto', 'membro'), name='participacao_unica_por_projeto')],
            },
        ),
    ]
